site_name: My Docs
theme:
  name: windmill
  features:
        - content.code.copy
        - content.code.annotate


  markdown_extensions:
  - md_in_html
  - toc:
      permalink: true
  - tables
  - admonition
  - def_list
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences


